events {}

http {
    server {
        listen 80;

        location /api/auth/ {
            proxy_pass http://ms-auth:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/stadium/ {
            proxy_pass http://ms-stadium:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/bookings/ {
            proxy_pass http://ms-bookings:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/notifications/ {
            proxy_pass http://ms-notifications:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
